### PR TITLE
Latest versions added

### PR DESCRIPTION
**Pull request by rc0r**
Versions 1.70b to 1.83b added.

### CODE REVIEW

**Comment by rc0r** [comment]
@arisada Seems you have abandoned this project. Do you mind transferring ownership to my account?

**Comment by arisada** [comment]
Indeed. How can I transfer ownership ?

**Comment by rc0r** [comment]
I'd say via https://github.com/arisada/afl-fuzz/settings -> Transfer Ownership. Never went through the process myself though.
If that doesn't work we might file a support request for the GH staff. In the past this worked quite well.

**Comment by arisada** [comment]
It says "rc0r/afl-fuzz already exists"

I guess one of us will have to delete or rename it. I don't have that many followers on the project anyway, I could delete it or replace it with a link to your repository

**Comment by rc0r** [comment]
I renamed my fork repo. Could you try again?

**Comment by arisada** [comment]
"rc0r already has a repository in the arisada/afl-fuzz network"

At this point I'm not sure what could work

**Comment by rc0r** [comment]
Ok, then we could resort to:
- merging this PR
- I'll delete my fork repo
- retry transfer

Is that fine for you?

**Comment by arisada** [comment]
We can retry, but that's unfortunate we have to lose followers to a fork when merging two related trees

**Comment by rc0r** [comment]
Yes, but the number of followers was small anyway. Fork repo deleted.

**Comment by rc0r** [comment]
Worked! Thanks!

**Pull request merged**
